version: '3.8'

services:
  flat_pulse_bot:
    container_name: flat_pulse_bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./database:/app/database
      - ./errors.log:/app/errors.log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
