services:
  bot:
    build: .
    container_name: flat_pulse_bot
    restart: always
    shm_size: '512mb'  # 🔥 Увеличиваем размер разделяемой памяти для стабильной работы Chrome
    env_file:
      - .env
    volumes:
      - ./database:/app/database  # Сохраняем базу данных при перезапусках контейнера
      - ./errors.log:/app/errors.log  # Пробрасываем лог ошибок для удобного чтения
